---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &app paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Paperless
        PAPERLESS_DBNAME: &dbname paperless
        PAPERLESS_DBHOST: &dbhost postgres16-rw.databases.svc.cluster.local

        PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {"openid_connect":{"APPS":[{"provider_id":"authelia","name":"Authelia","client_id":"{{ .PAPERLESS_OAUTH_CLIENT_ID }}","secret":"{{ .PAPERLESS_OAUTH_CLIENT_SECRET }}","settings":{"server_url":"https://auth.g-eye.io/.well-known/openid-configuration"}}]}}
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_PASS: "{{ .PAPERLESS_DBPASS}}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: "{{ .PAPERLESS_DBUSER }}"

  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: paperless
    - extract:
        key: cloudnative-pg
