---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openwebui
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openwebui-secret
    template:
      engineVersion: v2
      data:
        OPENAI_API_KEY: "{{ .OPENAPI_KEY }}"
  dataFrom:
    - extract:
        key: openai
