---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-config
  namespace: dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitea-config-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Gitea
        adminPassword: "{{ .ADMIN_PASSWORD }}"
        minioAccessKeyId: "{{ .MINIO_ACCESS_KEY_ID }}"
        minioSecretAccessKey: "{{ .MINIO_SECRET_ACCESS_KEY }}"
        # Authelia
        key: gitea
        secret: "{{ .GITEA_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: gitea
