---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backstage
  namespace: dev
spec:
  interval: 30m
  chart:
    spec:
      chart: backstage
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: backstage
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    nameOverride: backstage
    fullnameOverride: backstage

    image:
      repository: backstage/backstage
      tag: latest
      pullPolicy: IfNotPresent

    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: internal.g-eye.io
      hosts:
        - host: &host backstage.g-eye.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    backstage:
      appConfig:
        app:
          title: Backstage
          baseUrl: https://backstage.g-eye.io
        backend:
          baseUrl: https://backstage.g-eye.io
          cors:
            origin: https://backstage.g-eye.io
            methods: [GET, POST, PUT, DELETE]
            credentials: true

    postgresql:
      enabled: false

    externalPostgresql:
      host: postgres16-rw.database.svc.cluster.local
      port: 5432
      database: backstage

    persistence:
      enabled: true
      accessModes: ["ReadWriteOnce"]
      size: 10Gi
      storageClass: ceph-block
