---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app shlink
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      shlink:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.5@sha256:e0c87ce7df39d06b93f27cf2cc6a056611f13faaa88cc07ab4dc8bf7a85d0b11
            envFrom: &envFrom
              - secretRef:
                  name: shlink-secret
        containers:
          app:
            image:
              repository: ghcr.io/shlinkio/shlink
              tag: 3.7.4-non-root@sha256:b6553353135346c094e116207fca14fb4d5ce91468e657af92e3e9e730d579e7
            env:
              DEFAULT_DOMAIN: "ln.g-eye.io"
              DISABLE_TRACKING_FROM: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
              ENABLE_PERIODIC_VISIT_LOCATE: "true"
              IS_HTTPS_ENABLED: "true"
              PORT: &port 80
              REDIS_PUB_SUB_ENABLED: "true"
              REDIS_SERVERS: "redis-master.databases.svc.cluster.local:6379"
              SHELL_VERBOSITY: 3
              TASK_WORKER_NUM: 4
              TIMEZONE: Europe/Paris
              WEB_WORKER_NUM: 1
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /rest/health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "ln.g-eye.io"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      tmp:
        type: emptyDir
      tmp-data:
        type: emptyDir
        globalMounts:
          - path: /etc/shlink/data
