---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: drone-runner-kube
  namespace: drone
spec:
  interval: 5m
  chart:
    spec:
      chart: drone-runner-kube
      version: 0.1.10
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  values:
    rbac:
      buildNamespaces:
        - drone
    env:
      DRONE_RPC_HOST: drone.drone.svc:8080
      DRONE_RPC_PROTO: http
      DRONE_NAMESPACE_DEFAULT: drone
      DRONE_RPC_SECRET: ${SECRET_DRONE_RPC_SECRET}
      DRONE_SECRET_PLUGIN_ENDPOINT: http://drone-kubernetes-secrets.drone.svc:3000
      DRONE_SECRET_PLUGIN_TOKEN: ${SECRET_DRONE_SECRET_EXPORTER_KEY}
    resources:
      requests:
        cpu: 10m
        memory: 379M
      limits:
        cpu: 73m
        memory: 1218M
