---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drone
resources:
  - ./namespace.yaml
  - ./drone-runner.yaml
  - ./drone-secrets.yaml
  - ./drone.yaml
  - ./drone-secrets.sops.yaml
