---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: drone
spec:
  limits:
    - default:
        cpu: 1200m
      defaultRequest:
        cpu: 10m
      type: Container
