# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: drone
  namespace: security
type: Opaque
stringData:
  DRONE_STORAGE_POSTGRES_HOST: ENC[AES256_GCM,data:7k2lh49iyw9i3cVae3AE3BrgR2w=,iv:IruhdzHAEiN5kQWv97RYUlSA7Cl+ViB4CO7I4cWtop8=,tag:jYkMR10I1Um/PkWlZsNYnw==,type:str]
  DRONE_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:5ZwqZ4Q=,iv:x5yEFXTmMGlDhA2kZc1DWSLlYYGTQlY5Yg1wgKDhSwM=,tag:x3lRGd9ga/SrKdwieDWmCA==,type:str]
  DRONE_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:e6Rhvcest+YXNbWBQuROMFl9bvk=,iv:jRu10zObYe1tuNlIO3FukLKIROH05/iOpZzOMF4kByI=,tag:mDLc53+NZm+Q5IDiwkCFAw==,type:str]
  DRONE_STORAGE_POSTGRES_DATABASE: ENC[AES256_GCM,data:iA0/8vA=,iv:/xTx4p5Xr7GOfdDPusizg69URvOsuODe2KYBF67rwvU=,tag:oai89JOAiZ6HKu1JJ2v8sw==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:6Llo9GOtavdo6fRhQeF9aiFebJo=,iv:E/MRTVcbZocYZQLAyIZQ/lMjjM6cBbEhwpOxglrz9lE=,tag:eTjln3MyTmrdUeom/kx7lg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OTRPMUlkSm1WUC9vWGpF
        Kzc5cmFMVG4rWDNUeFdUSDYyVnVDNXRMZ1g4CnpFdHo3T1ovdWdLT1czamtGZkFH
        dWpqL0JoR3ZaN05VanpPZlFKSE5wbk0KLS0tIGxBSFhQMTV4TzJmREl6L3BqUUlq
        TzVJdld6ZXhaZlluc3lFOEtmTDNWc2sKv3VKMsEFq/uX8/sV5EHU73MG0P/ZlqTu
        dsQbvEVU6D3uIkQdqHoPwJ9jgme5hjADj8Tp89ZFxeKNHxNKfjR4WQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-08-29T11:41:11Z"
  mac: ENC[AES256_GCM,data:M+pyq4T2nNlAqh+rL/JYUVrkW1sNOpwD6Mmo/lfansOTzd6VIXfjv+8OokQz/9IYe4HP+01I5C2VL3f7cyPSPJj2UOXpyF0l3mqTV3PTYZtAM1JcVpjoHJoUuu+9HUknX23xmtb1VFcDiP4mG8pBdj21IT17y/EMZBT0C+c3b4E=,iv:s+0+6gZ9/OVRAVdHN/COcLJZ9oeYHXC4rynizUJqtjo=,tag:74dpiIsd52g5+K6hxmCfRw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
