---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: n8n-secret
    template:
      engineVersion: v2
      data:
        DB_TYPE: postgresdb
        DB_POSTGRESDB_DATABASE: &dbName n8n
        DB_POSTGRESDB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        DB_POSTGRESDB_USER: &dbUser "{{ .postgres_username }}"
        DB_POSTGRESDB_PASSWORD: &dbPass "{{ .postgres_password }}"
        DB_POSTGRESDB_PORT: "5432"

        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        N8N_ENCRYPTION_KEY: "{{ .n8n_encryption_key }}"
  dataFrom:
    - extract:
        key: n8n
    - extract:
        key: cloudnative-pg
