---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-chartmuseum
  labels:
    app.kubernetes.io/name: harbor-chartmuseum
    app.kubernetes.io/instance: harbor
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
