---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.9.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    storageClass:
      create: true
      name: nfs-slow
      parameters:
        server: expanse.internal
        share: /eros/Kubernetes
      mountOptions:
        - nfsvers=4.2
        - nconnect=8
        - hard
        - noatime
        - rsize=131072
        - wsize=131072
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
