---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lelabodamad
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lelabodamad-secret
    template:
      engineVersion: v2
      data:
        GOOGLE_PLACES_API_KEY: "{{ .GOOGLE_PLACES_API_KEY }}"
        MAILGUN_API_KEY: "{{ .MAILGUN_API_KEY }}"
        MAILGUN_DOMAIN: "{{ .MAILGUN_DOMAIN }}"
  dataFrom:
    - extract:
        key: lelabodamad
