---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twenty
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: twenty-secret
    template:
      engineVersion: v2
      data:
        # App
        APP_SECRET: "{{ .TWENTY_APP_SECRET }}"
        TWENTY_POSTGRES_USER: &dbUser "postgres"
        TWENTY_POSTGRES_PASS: &dbPass "{{ .POSTGRES_SUPER_PASS }}"
        TWENTY_POSTGRES_DB: &dbName "default"
        # MinIO S3 Storage
        MINIO_ENDPOINT: "nas.g-eye.tech:9000"
        AWS_ACCESS_KEY_ID: "{{ .MINIO_ROOT_USER }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MINIO_ROOT_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: &dbHost postgres16-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: twenty
    - extract:
        key: cloudnative-pg
    - extract:
        key: minio
