---
autoDirectNodeRoutes: true
bandwidthManager:
  enabled: true
  bbr: true
bpf:
  datapathMode: netkit
  masquerade: true
  preallocateMaps: true
  hostLegacyRouting: false
  mapDynamicSizeRatio: 0.0025
  clockProbe: true
  # tproxy: true
bgpControlPlane:
  enabled: true
  announce:
    loadbalancerIP: true
    podCIDR: true
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cluster:
  id: 1
  name: main
cni:
  exclusive: false
dashboards:
  enabled: true
devices: enp+
enableIPv4BIGTCP: true
endpointRoutes:
  enabled: true
envoy:
  rollOutPods: true
  healthPort: 9876
  readinessProbe:
    httpGet:
      path: /ready
      port: 9876
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
  livenessProbe:
    httpGet:
      path: /healthz
      port: 9876
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
gatewayAPI:
  enabled: true
  enableAlpn: true
  xffNumTrustedHops: 1
  connectTimeout: 5s
  requestTimeout: 30s
hubble:
  enabled: false
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.42.0.0/16
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: false
loadBalancer:
  algorithm: maglev
  mode: dsr
localRedirectPolicy: true
operator:
  dashboards:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 2
  rollOutPods: true
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: io.cilium/app
            operator: In
            values:
            - operator
        topologyKey: kubernetes.io/hostname
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
debug:
  verbose: ""
