---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage
  namespace: dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: backstage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: &dbHost "{{ .POSTGRES_HOST }}"
        #BACKSTAGE_DB_NAME: &dbName "{{ .BACKSTAGE_DB_NAME }}"
        POSTGRES_USER: &dbUser  "{{ .BACKSTAGE_DB_USERNAME }}"
        POSTGRES_PASSWORD: &dbPass  "{{ .BACKSTAGE_DB_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: backstage_plugin_catalog backstage_plugin_scaffolder backstage_plugin_search backstage_plugin_auth backstage_plugin_app backstage_plugin_proxy backstage_plugin_techdocs backstage_plugin_permission
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: backstage
    - extract:
        key: cloudnative-pg
