---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: &app backstage
  app.kubernetes.io/instance: *app
resources:
  - ./backstage-charts.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
