---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: harbor-webhook-token-secret
    template:
      data:
        token: "{{ .HARBOR_WEBHOOK_TOKEN_ELGATO }}"
  dataFrom:
    - extract:
        key: flux
