---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: blog
  namespace: flux-system
spec:
  image: harbor.g-eye.io/mgueye01/blog
  interval: 1m
  secretRef:
    name: regcred
  provider: generic
