apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: default
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:A3ntNUUkVyRZLpT38Hy3D5wiWL1v4fEEtqg0786IF6dL6vZ0yNLS3uGn4joxqrxSVkZkQuTZ8IIMDL2ULVspiY2PAGNUnZiSk/hVP3IV67/SSXIcsrmQm8DyYZDHk1OFbHXOWnRlvhXb/GWYnWpQoV7O6/G4YreHVMuihd4kAxAqOz3+1F2CfwUIstlRXB2yLxgVFFp2eoiAJNoWylltyog5WldiLjsJLCHXy59BoZsEVm+PbFuoP5Mn7kvi9yMJjddiY/9chyfVU24EeDQwVlLRAiTKWzdycCEyozhf0DRE1uiaLnzCLHlXnn4Fe9oES69sQ0zo2rNRDei+4AqWMcXM1Tu7dhQe1kbi,iv:oXRXJADeoHLqF0+5IzWx8AFuD8makrWZfSBruZ5ybQI=,tag:cyKc9Jg/yagYyfdHRWrvVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTUpoT0VnY3lVY0d0WVVm
            alV5NzFvSzVkY3gremZVMEtUNksxSmFFdTNJCit2cURybnV1YmtESlFkd3JZa0tR
            UTZTSXRkZFdSRW5BUzNwY1NJUkQweVEKLS0tIGYvRnBISFVBdVlJMFR0cml4WkdK
            RzFkclcrRkpQM2ZZdFVIZ05CQ0UyR3MKWw12SjpEgFHqL1qpgdlTcK4dTNmAa4hG
            pgvhAjROgFGw5rx4VX/jr336BynIqEIQhISpXuxk+ZX/GiHAmdVYUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T00:23:21Z"
    mac: ENC[AES256_GCM,data:lxy5KF6Pk1QsVLJIghDafCdg1ZRhqiIvGOx7CuJsIAuZZfABh9FActZROxpccksVx6/sV3mGFmvXrgfL+L137iX9pbazrEz7/ty/uHVT1AR7K+u4FtwoVZ+VpPwOyJnLbTG5Dvk1OFVZ+CXaVKRfE/aLuuXIyhys+ti+A8qrG54=,iv:ixfJYVGWoexuJEq6c6v57QLmn4F06iLFUz3b4jMDMUM=,tag:luuTGj6Sdu0q34DBZ2ik4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
