apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: default
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:rP1O+W2M4x0+HpAG2rWPQs59Tu9KntsZ4YBZgAIJlUEDXSiRrh6MC2KF0XbBMhUkGYXOmh1gLB1T2KovqGscBVUMqj99A561BY/AodW/RXjbwEBMZiszdrRKHtSpMhjcg0FBI//YFC/m71eowGwZCXvap8u4yD2hDoB0N5qViVC1Qn/vR0pHBTEuwgxd9SW+lMgNrXDQbglsLTp6hp80gX6l0Jfe0tbTrW+La35pMJOhP5Nf57jx88NwCVRwVrQDQQ+ovD9+O7xq2sUY5QeZ4TeUjt4QGJuk0MVIyD3dHGQppYs4N1Iajv5CRAfGVv7mW99fbQY7h5+FlAo7EnYZLj3NEv97WZaAiLafRBRVcDJKmbkm,iv:xL3zNQT2MNl7B5R9tkJojOcjmFPH8QUrxOlNz+oighQ=,tag:uKiwAS4mkneLqaia3syQSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTUpoT0VnY3lVY0d0WVVm
            alV5NzFvSzVkY3gremZVMEtUNksxSmFFdTNJCit2cURybnV1YmtESlFkd3JZa0tR
            UTZTSXRkZFdSRW5BUzNwY1NJUkQweVEKLS0tIGYvRnBISFVBdVlJMFR0cml4WkdK
            RzFkclcrRkpQM2ZZdFVIZ05CQ0UyR3MKWw12SjpEgFHqL1qpgdlTcK4dTNmAa4hG
            pgvhAjROgFGw5rx4VX/jr336BynIqEIQhISpXuxk+ZX/GiHAmdVYUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-25T23:37:24Z"
    mac: ENC[AES256_GCM,data:ZP/eXX5IQVJb5SGiCZrPktRvOcfydJyYsjcpM/buYPo1tVtBD/ncr+ME+dMphpaRH/vpzoLpeW0201ICMuU1vmj2cFMugKp3rCbqbr9qOx0/0tWFgcZ21DeyHw6vJJ7ClmjNlliM2Oipja6DWctFljILe94dlKJPJp385P9Ts7Y=,iv:1Gx76y18ktlA/eTzQqiMg+/YPXh8Mfp4g2mzz2n2jAY=,tag:BD/5W26G3G/S6txFi37DoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
