apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: default
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:piMk+7QPeSkwm/j+osb0fV1bFSbI0oECpnUo/niW1kdwpkYQelmqtIvVQcsfpLbeORzvaEyCwNZAhfqwG3/0htJHKOC8XisqaLhd4jTB2Gl0TF4ERmgL4WuV4i53MDHUSPwkP4pV7XA10TPKrgfJPjidjMKzqgqBC0jhhXrL/6bSkyMEr8//W/4NsucJ0GUoV7Z5UPP+vR0CfRE6ioIR7Az0OHq9cpsWSfCtJ0i+lo2342DXL12DcKotzIjDH9dCR61fMsTq4OM6ZflsqOd5/moIDGrWTAa2eawhRRyTCZ55i5rTwAiFu7dl1LakZSeX8jxZQ6PHzbBfBvnJhjYei+eGQQINfLrkKPym+9S29t678Lbc,iv:JQlWTzJYf4lVyCkiZB03Na7iXR6BXdZaKCH/itIpxLU=,tag:utb/qhDpLFQGyGX/hZtdMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTUpoT0VnY3lVY0d0WVVm
            alV5NzFvSzVkY3gremZVMEtUNksxSmFFdTNJCit2cURybnV1YmtESlFkd3JZa0tR
            UTZTSXRkZFdSRW5BUzNwY1NJUkQweVEKLS0tIGYvRnBISFVBdVlJMFR0cml4WkdK
            RzFkclcrRkpQM2ZZdFVIZ05CQ0UyR3MKWw12SjpEgFHqL1qpgdlTcK4dTNmAa4hG
            pgvhAjROgFGw5rx4VX/jr336BynIqEIQhISpXuxk+ZX/GiHAmdVYUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T00:52:24Z"
    mac: ENC[AES256_GCM,data:xFzOkXZgDFPNcXRvD3pmo7eSaw70K3r8P67M3U345eVl70BR0/fqNJkmdt+XJH4bq66+xRQFIibI/AFtYtgOVi9rPpCWND3Wxhkp6E6x/mjRCS0ABnjQeF2F0mOO0jRvdayrw23J+10O9QUHYphWTuDjUog1LwpIgKi1LKCZ8UY=,iv:7LsJ4UPqVNB9k2xctxqQjAdygMpEqH6H4K940M8xrDE=,tag:6+4C4nQstjCvHeSApTHgIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
