---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nebula-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nebula-sync-secret
    template:
      data:
        PRIMARY: "http://192.168.0.196|{{ .PIHOLE_API_KEY }}"
        REPLICAS: "http://192.168.0.212|{{ .PIHOLE_API_KEY }}"
  dataFrom:
    - extract:
        key: pihole
