---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: g-eye-io
spec:
  secretName: g-eye-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: g-eye.io
  dnsNames:
    - g-eye.io
    - "*.g-eye.io"
