# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: buildkitd
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.6.1
  values:
    controllers:
      buildkitd:
        containers:
          app:
            args:
            - --root
            - /cache
            - --addr
            - unix:///run/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
            - --tlscacert
            - /certs/ca.pem
            - --tlscert
            - /certs/cert.pem
            - --tlskey
            - /certs/key.pem
            image:
              repository: ghcr.io/vaskozl/buildkit
              tag: 0.18.2@sha256:8fa48d383e3ac6360291c779a98be8fc283b0f5fc59d520b13d97be7de730e63
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                cpu: 2
                memory: 0.6Gi
              requests:
                cpu: 200m
                ephemeral-storage: 10Gi
                memory: 0.6Gi
            securityContext:
              privileged: true
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/arch: amd64
    persistence:
      cache:
        type: emptyDir
      certs:
        globalMounts:
        - path: /certs
        name: buildkit-daemon-certs
        type: secret
    service:
      app:
        controller: buildkitd
        ports:
          mtls:
            enabled: true
            port: 1234
