---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app teslamate
  namespace: flux-system
spec:
  targetNamespace: observability
  interval: 10m
  path: "./kubernetes/main/apps/observability/teslamate/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: external-secrets
    - name: rook-ceph-cluster
    - name: cloudnative-pg-cluster
    - name: mosquitto
  postBuild:
    substitute:
      APP: *app
      GATUS_PATH: /healthcheck
