---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
data:
  openclaw.json: |
    {
      "gateway": {
        "mode": "local",
        "bind": "lan",
        "port": 18789,
        "controlUi": {
          "enabled": true,
          "allowInsecureAuth": true,
          "allowedOrigins": ["https://openclaw.g-eye.io"]
        },
        "auth": {
          "mode": "token"
        }
      },
      "channels": {
        "telegram": {
          "enabled": true
        }
      },
      "plugins": {
        "deny": ["bonjour"]
      }
    }
