---
directories:
  downloads: /media/Downloads/soulseek/complete
  incomplete: /media/Downloads/soulseek/incomplete
flags:
  no_version_check: true
integration:
  scripts:
    beets:
      on:
        - DownloadDirectoryComplete
      run: /bin/sh /scripts/beets.sh "$DATA"
    debug:
      on:
        - DownloadFileComplete
        - DownloadDirectoryComplete
      run: echo "$DATA" >> /config/debug.txt
metrics:
  enabled: true
  url: /metrics
  authentication:
    disabled: true
permissions:
  file:
    mode: 750
remote_configuration: false
shares:
  directories:
    - /media/Downloads/soulseek/shared
  filters:
    - \.ini$
    - Thumbs.db$
    - \.DS_Store$
