---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: drone
  namespace: drone
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.8@sha256:0141cf427c47f2d534711a3f9e8c5f9008bc6b585463ccd9288cf0f027e20deb
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: drone
                key: DRONE_STORAGE_POSTGRES_HOST
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: drone
                key: DRONE_STORAGE_POSTGRES_DATABASE
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: drone
                key: POSTGRES_SUPER_PASS
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: drone
                key: DRONE_STORAGE_POSTGRES_USERNAME
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: drone
                key: DRONE_STORAGE_POSTGRES_PASSWORD
