---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname buildkit
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/dev/buildkit/app
  targetNamespace: dev
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  prune: true
  wait: false
  interval: 10m
