---
originRequest:
  originServerName: external.g-eye.io

ingress:
  - hostname: g-eye.io
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.g-eye.io"
    service: *svc
  - service: http_status:404
