---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secretName harbor-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretName
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Harbor
        password: "{{ .HARBOR_POSTGRES_PASS }}"
        HARBOR_ADMIN_PASSWORD: "{{ .HARBOR_ADMIN_PASS }}"
        # Postgres DB
        POSTGRES_DB: &dbname registry
        POSTGRES_HOST: &dbhost postgres16-rw.database.svc.cluster.local
        POSTGRES_USER: &dbuser "{{ .HARBOR_POSTGRES_USER }}"
        POSTGRES_PASS: &dbpass "{{ .HARBOR_POSTGRES_PASS }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: harbor
    - extract:
        key: cloudnative-pg
