---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smtp-relay
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      smtp-relay:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/foxcpp/maddy
              tag: 0.8.0@sha256:7e4a6560cee8bf11a8fa6f624903cab38e8a3fb0e941a7d27dacf556038546cd
            env:
              SMTP_RELAY_SMTP_PORT: &port 25
              SMTP_RELAY_METRICS_PORT: &metricsPort 8080
              SMTP_RELAY_SERVER_PORT: 465
            envFrom:
              - secretRef:
                  name: smtp-relay-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: smtp-relay
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: smtp-relay.g-eye.io
          lbipam.cilium.io/ips: 192.168.10.83
        ports:
          http:
            primary: true
            port: *metricsPort
          smtp:
            port: *port
    serviceMonitor:
      app:
        serviceName: smtp-relay
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      config:
        type: configMap
        name: smtp-relay-configmap
        globalMounts:
          - path: /data/maddy.conf
            subPath: maddy.conf
            readOnly: true
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
