---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crds/gateway.envoyproxy.io_backends.yaml
  - ./crds/gateway.envoyproxy.io_backendtrafficpolicies.yaml
  - ./crds/gateway.envoyproxy.io_clienttrafficpolicies.yaml
  - ./crds/gateway.envoyproxy.io_envoyextensionpolicies.yaml
  - ./crds/gateway.envoyproxy.io_envoypatchpolicies.yaml
  - ./crds/gateway.envoyproxy.io_envoyproxies.yaml
  - ./crds/gateway.envoyproxy.io_httproutefilters.yaml
  - ./crds/gateway.envoyproxy.io_securitypolicies.yaml
  - ./envoy.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
