---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflared-tunnel-secret
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .CLOUDFLARE_ACCOUNT_TAG }}",
            "TunnelSecret": "{{ .CLOUDFLARE_TUNNEL_SECRET }}",
            "TunnelID": "458d945d-4ab9-4c56-bf67-5a0fe9caa116"
          }
  dataFrom:
    - extract:
        key: cloudflare
