---
# yaml-language-server: $schema=https://kubernetes-schemas.g-eye.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Paperless
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: &dbname paperless
        PAPERLESS_DBHOST: &dbhost postgres16-rw.database.svc.cluster.local
        PAPERLESS_DBUSER: "{{ .PAPERLESS_DBUSER }}"
        PAPERLESS_DBPASS: "{{ .PAPERLESS_DBPASS }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_PASS: "{{ .PAPERLESS_DBPASS}}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: "{{ .PAPERLESS_DBUSER }}"
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: cloudnative-pg
