---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name plex-exporter
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PLEX_TOKEN: '{{ .PLEX_TOKEN }}'
  dataFrom:
    - extract:
        key: plex
