---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rybbit
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rybbit-secret
    template:
      engineVersion: v2
      data:
        # Domain Configuration
        DOMAIN_NAME: "analytics.g-eye.io"
        BASE_URL: "https://analytics.g-eye.io"

        # Authentication Secret
        BETTER_AUTH_SECRET: "{{ .RYBBIT_AUTH_SECRET }}"

        # PostgreSQL Configuration
        RYBBIT_POSTGRES_USER: &dbUser "postgres"
        RYBBIT_POSTGRES_PASS: &dbPass "{{ .POSTGRES_SUPER_PASS }}"
        RYBBIT_POSTGRES_DB: &dbName "rybbit"
        POSTGRES_HOST: "postgres16-rw.databases.svc.cluster.local"
        POSTGRES_PORT: "5432"
        POSTGRES_DB: *dbName
        POSTGRES_USER: *dbUser
        POSTGRES_PASSWORD: *dbPass

        # ClickHouse Configuration
        CLICKHOUSE_HOST: "http://rybbit-clickhouse:8123"
        CLICKHOUSE_DB: "analytics"
        CLICKHOUSE_USER: "default"
        CLICKHOUSE_PASSWORD: "{{ .RYBBIT_CLICKHOUSE_PASSWORD }}"

        # Redis Configuration
        REDIS_HOST: "redis-master.databases.svc.cluster.local"
        REDIS_PORT: "6379"
        REDIS_PASSWORD: ""

        # Feature Flags
        DISABLE_SIGNUP: "false"
        DISABLE_TELEMETRY: "true"

        # Public URLs
        NEXT_PUBLIC_BACKEND_URL: "https://analytics.g-eye.io"
        NEXT_PUBLIC_DISABLE_SIGNUP: "false"

        # Postgres Init Container Variables
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: "postgres16-rw.databases.svc.cluster.local"
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: rybbit
    - extract:
        key: cloudnative-pg
