---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: kube-system
  name: nfs-subdir-external-provisioner
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: nfs-subdir-external-provisioner
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
  interval: 1h
  values:
    nfs:
      server: "192.168.0.18"
      # server: "nas.g-eye.tech"
      path: /volume1/CLOUDNATIVE1
    storageClass:
      name: nfs-client
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      archiveOnDelete: true
      pathPattern: ${.PVC.namespace}-${.PVC.name}
