---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crawl4ai
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: crawl4ai-secret
    template:
      engineVersion: v2
      data:
        CRAWL4AI_API_TOKEN: "{{ .CRAWL4AI_API_TOKEN }}"
  dataFrom:
    - extract:
        key: crawl4ai
