---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: irqbalance
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      irqbalance:
        type: daemonset
        containers:
          app:
            image:
              repository: ghcr.io/buroa/irqbalance
              tag: 1.9.4@sha256:f6d487e66a2ce0b651d0d7da291ce54c325ed79b34ffad5baef1123160323be6
            env:
              IRQBALANCE_BANNED_CPULIST: 8-17 # These are E-cores
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 128Mi
            securityContext:
              privileged: true
    defaultPodOptions:
      hostIPC: true
      hostPID: true
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
    persistence:
      run:
        type: emptyDir
        globalMounts:
          - path: /run/irqbalance
