---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: drone-secrets
  namespace: drone
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.drone.io
      chart: drone-kubernetes-secrets
      version: 0.1.4
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
      interval: 5m
  values:
    rbac:
      enabled: true
      secretNamespace: drone
    env:
      KUBERNETES_NAMESPACE: drone
      SECRET_KEY: DRONE_SECRET_EXPORTER_KEY
    resources:
      requests:
        cpu: 10m
        memory: 379M
      limits:
        cpu: 73m
        memory: 1218M
  valuesFrom:
    - targetPath: env.DRONE_SECRET_EXPORTER_KEY
      kind: Secret
      name: drone-secrets
      valuesKey: DRONE_SECRET_EXPORTER_KEY
