---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app harbor
  namespace: flux-system
spec:
  targetNamespace: dev
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/dev/harbor/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: rook-ceph-cluster
