---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./externalsecret.yaml
  - ../../../../../shared/templates/gatus/guarded
  - ./helmrelease.yaml
  - dashboards
labels:
  - pairs:
      app.kubernetes.io/name: teslamate
      app.kubernetes.io/instance: teslamate
