apiVersion: v1
kind: Secret
metadata:
  name: twenty-mcp-secret
  namespace: dev
type: Opaque
stringData:
  TWENTY_API_KEY: ENC[AES256_GCM,data:PvAUNelJxm3bJ7xt/x4cDiOJP3lg7KYn94GbG6JDe3ewevdMhz8VOM5og6kADsZ8OyAcPmuhLBsAsAqm3fX3D4hZljm00eKxKYwkqvvChBmrG4N8XBXQ2pOcLane2zQhwoCko0akmkOvFOBd8f6iuxoL+e+W6mPv1yTWxaiy0YeQSOauQjojzeX+KKbWP1RlaVwUp4eA4DwNALTW1o0pWcWErnothgYTgnWbSAUQwxbJXHdQSMx05+Sy9Kxk6p3elmxRKY5eS3S9IavRtJHhg4znu5jMtMtBkPAJYK/2haHNkl2LKmB7v3NoErRq0FGAmwjCCaIJHCG1aOrXe7ToipmzJueyJN7hQJHLLu/Gp+NdLloS3+nvq+DdH6O6Om3ciZ652t0W/tkgTwIGsQK7Zv5kvBc/JyTDwbWfz1Re1bP4YkGbXsj9WXzX7x9W6ES1G1qlxhQ=,iv:0dTlh98699fBaMy6YvxEtheCUJQipxMcTXP+KDOxius=,tag:f9/JCCmbWwI8XFrw+ujxow==,type:str]
sops:
  age:
    - recipient: age1ufv6l98ntd5t4tulqs9rmkjdtuytvt7ptj4uvjdhqaff93fpdf7s5rr4uk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bnRad0FDUk1La2JOR1c2
        UFQxbXNtTWRRaVNITkVDbnh4RFZxeU9HMEdJCjhzZE1hU2VFRmRLNjdkMXMvMDN3
        NW9NZk5JbjEwRmZqL3JjT0RlcEtFeVUKLS0tIHdWMGdNc094T01RK1IyRENhU2I0
        empuZC9sZmErakEvWFVHTGI4TmVBUWsKn5qEaI5FscAnT9ZN3E6xrYPPNZ5wdhgN
        2AJI/LP5932McyHVmj6Jq7tfe7221ZZiPlxHIxLKS501FXSlZSYstA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-08T13:54:34Z"
  mac: ENC[AES256_GCM,data:lGIPuMykb/ORfPT1ELEpfQ04RSFvHN22TkLfPpqnlBYJOVaszoWx0u+PPI4waH2KlDjRB/SY2pCcmJQJ30/mGWE9hGSFKOqoAR0/coJX7w6WtKo+ENOHju/KGxf7ddyNDFNCsPsewzWb9QiV5uvgQsc+5b3k7/L/jxmPKcr5u54=,iv:rTGkLyucSTaQEgDYg5sQue36MRO+GTlDtT0mvPEuf70=,tag:6AWjLF4eNEd/mChPx4pq1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
